# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "jadesystems/rails5"
  config.vm.box_version = "0.5.0"
  config.vm.box_check_update = true

  config.vm.provider "virtualbox" do |v|
    v.linked_clone = true
  end

  # Queremos a VM acessível na rede? Com que IP?
  # Descomentar e fazer vagrant reload
  config.vm.network "public_network" #, ip: "192.168.10.50"

  # Precisamos de mais portas host <-> guest?
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # É necessário alterar hw da VM?
  # config.vm.provider "virtualbox" do |vb|
  #   vb.memory = "2048"
  #   vb.cpus = 1
  # end

  # Queremos correr alguma configuração extra no fim?
  # (coisas mais complexas com pupper, ansible, chef)
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
